CI fix #2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,32 +6,32 @@ on:
       - master
 
 jobs:
-  define-matrix:
-    runs-on: ubuntu-latest
-    outputs:
-      matrix: ${{ steps.eval-matrix.outputs.matrix }}
-
-    steps:
-      - uses: actions/checkout@v6
-
-      - uses: DeterminateSystems/determinate-nix-action@v3 
-
-      - id: eval-matrix
-        name: Generate Nix Matrix
-        run: |
-          set -Eeu
-          matrix="$(nix eval --accept-flake-config --json '.#githubActions.matrix')"
-          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
+  # define-matrix:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     matrix: ${{ steps.eval-matrix.outputs.matrix }}
+  #
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #
+  #     - uses: DeterminateSystems/determinate-nix-action@v3 
+  #
+  #     - id: eval-matrix
+  #       name: Generate Nix Matrix
+  #       run: |
+  #         set -Eeu
+  #         matrix="$(nix eval --accept-flake-config --json '.#githubActions.matrix')"
+  #         echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
 
   build:
     runs-on: ubuntu-latest
-    needs: define-matrix
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
-    concurrency:
-      group: ${{ github.workflow }}.${{ github.event.pull_request.number || github.ref }}.${{ matrix.host }}
-      cancel-in-progress: true
+    # needs: define-matrix
+    # strategy:
+    #   fail-fast: false
+    #   matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
+    # concurrency:
+    #   group: ${{ github.workflow }}.${{ github.event.pull_request.number || github.ref }}.${{ matrix.host }}
+    #   cancel-in-progress: true
 
     steps:
       - uses: actions/checkout@v6
@@ -41,7 +41,6 @@ jobs:
         with:
           extra-conf: |
             max-jobs = auto
-            builders = @/etc/nix/machines
             max-substitution-jobs = 64
             http-connections = 64
 
@@ -51,4 +50,4 @@ jobs:
             ${{ secrets.BUILDER_SSH_KEY }}
 
       - name: Build ${{ matrix.host }}
-        run: nix run github:Mic92/nix-fast-build -- --remote github@builder.vedenemo.dev --no-download --no-nom --skip-cached --option accept-flake-config true --flake ".#${{ matrix.host }}"
+        run: nix run github:Mic92/nix-fast-build -- --remote jrautiola@builder.vedenemo.dev --no-download --no-nom --skip-cached --option accept-flake-config true"
